# -*- coding: utf-8 -*-

__author__ = 'Hemanth Sana'
__email__ = 'hesa@nmbu.no'


class LCGRand:
    def __init__(self, seed):
        self.seed = seed

    def rand(self):
        a = 16807
        m = 2 ** 31 - 1
        self.seed = a * self.seed % m
        return self.seed


class ListRand:
    def __init__(self, number_list):
        self.number_list = number_list
        self.index = -1

    def rand(self):
        self.index += 1
        if self.index < len(self.number_list):
            return self.number_list[self.index]
        else:
            raise RuntimeError()


if __name__ == "__main__":
    num_list = ([23, 56, 64, 12, 35, 76, 17, 99, 81, 44, 8, 33])
    list_rand = ListRand(num_list)
    print('Random Numbers generated by ListRand function are: ')
    for run in range(10):
        print(list_rand.rand())

    lcg_rand = LCGRand(200)
    print('Random Numbers generated by LCGRand function are : ')
    for run in range(10):
        print(lcg_rand.rand())
